In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [4]:
data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv',sep=";")

In [5]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [6]:
train , test = train_test_split(data)

In [7]:
train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1394,6.4,0.570,0.14,3.90,0.070,27.0,73.0,0.99669,3.32,0.48,9.2,5
485,10.2,0.670,0.39,1.90,0.054,6.0,17.0,0.99760,3.17,0.47,10.0,5
556,10.9,0.530,0.49,4.60,0.118,10.0,17.0,1.00020,3.07,0.56,11.7,6
1037,7.3,0.910,0.10,1.80,0.074,20.0,56.0,0.99672,3.35,0.56,9.2,5
1471,6.7,0.700,0.08,3.75,0.067,8.0,16.0,0.99334,3.43,0.52,12.6,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1012,7.7,1.005,0.15,2.10,0.102,11.0,32.0,0.99604,3.23,0.48,10.0,5
464,11.5,0.315,0.54,2.10,0.084,5.0,15.0,0.99870,2.98,0.70,9.2,6
317,9.6,0.770,0.12,2.90,0.082,30.0,74.0,0.99865,3.30,0.64,10.4,6
898,8.3,0.310,0.39,2.40,0.078,17.0,43.0,0.99444,3.31,0.77,12.5,7
575,12.3,0.270,0.49,3.10,0.079,28.0,46.0,0.99930,3.20,0.80,10.2,6

In [8]:
test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
784,7.1,0.59,0.01,2.5,0.077,20.0,85.0,0.99746,3.55,0.59,9.8,5
538,12.9,0.35,0.49,5.8,0.066,5.0,35.0,1.00140,3.20,0.66,12.0,7
423,10.5,0.24,0.47,2.1,0.066,6.0,24.0,0.99780,3.15,0.90,11.0,7
316,9.6,0.56,0.23,3.4,0.102,37.0,92.0,0.99960,3.30,0.65,10.1,5
486,10.2,0.67,0.39,1.9,0.054,6.0,17.0,0.99760,3.17,0.47,10.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1539,7.2,0.39,0.32,1.8,0.065,34.0,60.0,0.99714,3.46,0.78,9.9,5
541,9.5,0.46,0.49,6.3,0.064,5.0,17.0,0.99880,3.21,0.73,11.0,6
1425,8.3,0.26,0.37,1.4,0.076,8.0,23.0,0.99740,3.26,0.70,9.6,6
269,11.5,0.18,0.51,4.0,0.104,4.0,23.0,0.99960,3.28,0.97,10.1,6
562,9.0,0.54,0.49,2.9,0.094,41.0,110.0,0.99820,3.08,0.61,9.2,5

In [9]:
data.shape

(1599, 12)

In [10]:
train.shape

(1199, 12)

In [11]:
test.shape

(400, 12)